#ifndef ARSERVER_COMMON_CONSTANT_H
#define ARSERVER_COMMON_CONSTANT_H

enum SImageFormat
{
    SIMAGE_FORMAT_NON       = -1,
    SIMAGE_FORMAT_YUV_NV21  = 1000, //YYYYYYYY UVUV
    SIMAGE_FORMAT_YUV_NV12  = 1001, //YYYYYYYY VUVU
    SIAMGE_FORMAT_YUV_I420  = 1002, //YYYYYYYY UU VV
    SIMAGE_FORMAT_YUV_YV12  = 1003, //YYYYYYYY VV UU
    SIMAGE_FORMAT_TOF_SHORT = 1004
};

enum ArAxisUpMode{
    AR_AXIS_UP_MODE_Y = 0,
    AR_AXIS_UP_MODE_Z = 1,
};

enum Rotation {
    ROTATION_0 = 0,
    ROTATION_90 = 1,
    ROTATION_180 = 2,
    ROTATION_270 = 3
};

enum MatrixConvertFlag
{
    NO_CONVERT,
    LANDSCAPERIGHT_TO_PORTRAIT,
    LANDSCAPERIGHT_TO_LANDSCAPELEFT,
    LANDSCAPERIGHT_TO_REVERSEPORTAIT
};

enum ARVertexFormat {
    ARVERTEX_FORMAT_UNKNOWN = -1,
    ARVERTEX_FORMAT_3D_POSITION = 0,
    ARVERTEX_FORMAT_3D_POSITION_NORMAL = 1,
    ARVERTEX_FORMAT_3D_POSITION_NORMAL_COLOR = 2
};

enum ARPlaneType{
    ARPLANE_TYPE_UNKNOWN = -1,
    ARPLANE_TYPE_UPWARD_FACING = 0,
    ARPLANE_TYPE_DOWNWARD_FACING = 1,
    ARPLANE_TYPE_VERTICAL = 2
};

enum COORDINATE_AXIS {
    AXIS_X,
    AXIS_Y,
    AXIS_Z
};


#define RECEEVE_MAGIC_NUMBER 0x3a3b
#define SEND_MAGIC_WORD      0xabcd
#define CAMERA_RGB 2000
#define CAMERA_RGBD 2100

const int VERSION_1 = 0xff1;

#endif //ARSERVER_COMMON_CONSTANT_H
